apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-backend

  template:
    metadata:
      labels:
        app: flask-backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: flask-backend

          image: 250368537874.dkr.ecr.us-east-1.amazonaws.com/flask-backend:v1

          ports:
            - containerPort: 5000
              protocol: TCP

          env:
            - name: AWS_REGION
              value: "us-east-1"

            - name: SECRET_NAME
              value: "rds!db-bafb2a82-2aea-4936-b5b0-eb4930d41318"

            - name: DB_HOST
              value: "database-1.cu9eqo0c4f5w.us-east-1.rds.amazonaws.com"

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: "dev"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
