apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: saikiran
  region: us-east-1

managedNodeGroups:
  - name: nginx-workers
    instanceType: t3.medium

    minSize: 1
    desiredCapacity: 2
    maxSize: 5

    volumeSize: 20
    volumeType: gp3

    labels:
      app: nginx

    tags:
      Environment: demo
      ManagedBy: eksctl

